CREATE DATABASE [Drivers]
GO
USE [Drivers]
GO

CREATE TABLE City(
	ID INT IDENTITY PRIMARY KEY,
	[Name] NVARCHAR(100) NOT NULL,
	PostCode NVARCHAR(20) NOT NULL,
)
GO

CREATE TABLE [Address](
	ID INT IDENTITY PRIMARY KEY,
	CityID INT FOREIGN KEY REFERENCES City(ID) NOT NULL,
	Street NVARCHAR(100) NOT NULL,
	HouseNumber NVARCHAR(100) NOT NULL,	
)
GO

CREATE TABLE PassportInfo(
	ID INT IDENTITY PRIMARY KEY,
	Seria NVARCHAR(10) NOT NULL,
	Number NVARCHAR(10) NOT NULL,
)
GO

CREATE TABLE Person(
	ID INT IDENTITY PRIMARY KEY,
	[LastName] NVARCHAR(100) NOT NULL,
	[Name] NVARCHAR(100) NOT NULL,
	[MiddleName] NVARCHAR(100) NOT NULL,
	PassportInfoID INT FOREIGN KEY REFERENCES PassportInfo(ID) NOT NULL,
	RegistrationAddressID INT FOREIGN KEY REFERENCES [Address](ID) NOT NULL,
	LifeAddressID INT FOREIGN KEY REFERENCES [Address](ID) NOT NULL,
)
GO

CREATE TABLE JobInfo(
	ID INT IDENTITY PRIMARY KEY,
	JobPlace NVARCHAR(100),
	JobRole NVARCHAR(100),
)
GO

CREATE TABLE Driver(
	ID INT IDENTITY PRIMARY KEY,
	PersonID INT FOREIGN KEY REFERENCES Person(ID) NOT NULL,
	JobInfoID INT FOREIGN KEY REFERENCES JobInfo(ID) NOT NULL,
	MobilePhone NVARCHAR(20) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	Photo IMAGE,
	[Description] NVARCHAR(500),
)
GO

CREATE TABLE Car(
	ID INT IDENTITY PRIMARY KEY,
	DriverID INT FOREIGN KEY REFERENCES Driver(ID) NOT NULL,
	Number NVARCHAR(100) NOT NULL,
)
GO

CREATE TABLE [Data](
	ID INT IDENTITY PRIMARY KEY,
	CarID INT FOREIGN KEY REFERENCES Car(ID) NOT NULL,
	Region NVARCHAR(50) NOT NULL,
	LicenseNumber NVARCHAR(100) NOT NULL,
	CreationDate DATETIME NOT NULL,
	Photo IMAGE,
)
GO

CREATE TABLE Fine(
	ID INT IDENTITY PRIMARY KEY,
	DataID INT FOREIGN KEY REFERENCES [Data](ID) NOT NULL,
	Success BIT NOT NULL,
)
GO