CREATE DATABASE [Gibdd]
GO
USE [Gibdd]
GO

CREATE TABLE Region(
	ID INT IDENTITY PRIMARY KEY,
	EngName NVARCHAR(100) NOT NULL,
	RusName NVARCHAR(100) NOT NULL,
	SubjectCode INT,
	IsoCode NVARCHAR(15),
	OkatoCode NVARCHAR(15),
)
GO

CREATE TABLE RegCode(
	ID INT IDENTITY PRIMARY KEY,
	Code INT NOT NULL,
	RegionID INT FOREIGN KEY REFERENCES Region(ID) NOT NULL,
)
GO