//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriversWebApi.EntityFramework
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Data()
        {
            this.Fine = new HashSet<Fine>();
        }
    
        public int ID { get; set; }
        public int CarID { get; set; }
        public string Region { get; set; }
        public string LicenseNumber { get; set; }
        public System.DateTime CreationDate { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Car Car { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Fine> Fine { get; set; }
    }
}
