//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriversWebApi.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fine
    {
        public int ID { get; set; }
        public int DataID { get; set; }
        public bool Success { get; set; }
    
        public virtual Data Data { get; set; }
    }
}
